### PR TITLE
Added a spotify inspired dark background

### PR DESCRIPTION
**Pull request by SkelleyBelly**
**Looks best with upgraded icons in PR: https://github.com/walktalkchalk/talking-tabs/pull/6**

- Green on black design with white text

- Responsive icons

- Sexy as hell

Screenshot 2019-10-14 at 21 31 31

### CODE REVIEW

**Comment by dngrhm** [comment]
Looks nice!   I'm not seeing any changes outside of changes to the yarn.lock file 🤷‍♂Can you check if you committed all your changes and pushed them?  Thanks!!

"12 hours of Relaxing Fireplace Sounds" x 7 😆🤣😂

**Comment by SkelleyBelly** [comment]
Ah my bad! Looks like I didn’t commit properly. Let me check it out and get it pushed back up.

The relaxing fireplace sounds were definitely required to keep it up and running! And they’ve actually very relaxing, can fully recommend

**Comment by SkelleyBelly** [comment]
That's been updated now. Turns out it was lost in my stash from when i made a new branch. I remerged my fork as well so this works with the recent icon update too

**Comment by dngrhm** [comment]
Thanks for the PR.  I decided to go a different route.  Hope you had a successful Hacktoberfest!

**Pull request closed without merging**
